services:
  app:
    build: .
    image: time-report:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - C:/Users/jimmy.vilen/Dropbox/db:/app/data
    environment:
      ConnectionStrings__Default: "Data Source=/app/data/local.db"
